import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
      <title>Zingnew | chuyển tiền</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="og:title" content="Timo gửi tặng bạn số tiền" />
        <meta name="og:image" content="https://timo.vn/wp-content/uploads/Main-banner_new-logo_VN.jpg" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Head>
      <title>Zingnew | chuyển tiền</title>

      <meta property="fb:app_id" content="2034212100232051"></meta>

      <meta name="description" content="Doanh nghiệp cho rằng phải hạn chế xuất khẩu tiểu ngạch để hướng đến chính ngạch."></meta>
      <meta name="keywords" content="xuất khẩu nông sản sang trung quốc"></meta>
      <meta name="googlebot" content="noarchive"></meta>
      <meta name="robots" content="noarchive"></meta>
      <meta property="og:site_name" content="ZingNews.vn"></meta>
      <meta property="og:rich_attachment" content="true"></meta>
      <meta property="article:publisher" content="https://www.facebook.com/zing.vn"></meta>
      <meta property="og:type" content="article"></meta>
      <meta property="og:image" content="https://znews-photo-fbcrawler.zadn.vn/w1250/Uploaded/bfjysesfzyr/2022_01_06/xuat_khau_sang_TQ.jpg"></meta>
      <meta property="og:image:width" content="1200"></meta>
      <meta property="og:image:height" content="630"></meta>
      <meta property="article:modified_time" content="2022-01-06T15:11:01+0700"></meta>
      <meta property="article:published_time" content="2022-01-06T13:12:05+0700"></meta>
      <meta property="og:title" content="Cần hướng đến xuất khẩu chính ngạch"></meta>

      <meta property="og:description" content="Doanh nghiệp cho rằng phải hạn chế xuất khẩu tiểu ngạch để hướng đến chính ngạch."></meta>
      </Head> */}



      <main className={styles.main}>
        <h1 className={styles.title}>
          About
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
